ENH: Some improvements to NFS test
NSLS-II/controls-doctor pull request #2
Opened 2017-06-04 03:00 UTC by stuartcampbell

Added `sync`s around the NFS write performance test using `dd`. 

NOTE: I haven't actually tested this on a real NSLS-II machine yet
(was having issues logging in remotely)

2017-07-11 14:28 UTC, danielballan requested changes

2017-07-11 14:28 UTC, danielballan commented on controls_doctor/_doctor.py
> +             'bs=1048576', 'count=1', '; sync'], stderr=subprocess.STDOUT).decode()
Following up from an in-person conversation awhile ago, I don't think the time in the second `sync` will be counted in the performance test. May something blunter like a plain old `time` command would be more robust. Accuracy is more important than precision here.

2017-07-13 21:50 UTC, stuartcampbell commented
Removed `syncs` - I agree that just timing the `dd` will be a better approach.  For now, I've just made this PR be just to clean up the temp file.

2017-07-13 22:50 UTC, danielballan approved these changes

2017-07-13 22:50 UTC, merged